# permissions for end users to edit nginxclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxcluster-editor-role
rules:
- apiGroups:
  - fixation.example.com
  resources:
  - nginxclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fixation.example.com
  resources:
  - nginxclusters/status
  verbs:
  - get
